/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface FormValidateSubmit {
    }
}
declare global {
    interface HTMLFormValidateSubmitElement extends Components.FormValidateSubmit, HTMLStencilElement {
    }
    var HTMLFormValidateSubmitElement: {
        prototype: HTMLFormValidateSubmitElement;
        new (): HTMLFormValidateSubmitElement;
    };
    interface HTMLElementTagNameMap {
        "form-validate-submit": HTMLFormValidateSubmitElement;
    }
}
declare namespace LocalJSX {
    interface FormValidateSubmit {
    }
    interface IntrinsicElements {
        "form-validate-submit": FormValidateSubmit;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "form-validate-submit": LocalJSX.FormValidateSubmit & JSXBase.HTMLAttributes<HTMLFormValidateSubmitElement>;
        }
    }
}
