/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { FormDefinition, FormResult } from "./ui/types";
import { TextFieldTypes } from "@ionic/core";
export namespace Components {
    interface BasicUiInputElement {
        /**
          * @param form
          * @see UIInputElement #bindNativeEvents
         */
        "bindNativeEvents": (form: FormDefinition) => Promise<void>;
        /**
          * HTML5 validation methods. Will be bound via {@link bindNativeInput} during the 'componentWillLoad' lifecyle
          * @see UIInputElement #checkValidity
          * @see HTMLInputElement #checkValidity
         */
        "checkValidity": () => Promise<any>;
        /**
          * sets the field as disabled
         */
        "disabled"?: boolean;
        /**
          * Retrieves the native {@link HTMLInputElement}
         */
        "getNativeElement": () => Promise<HTMLInputElement>;
        /**
          * Returns the field value
         */
        "getValue": () => Promise<any>;
        /**
          * will translate to the form id attribute
         */
        "inputId": string;
        /**
          * will translate to the form name attribute
         */
        "inputName": string;
        /**
          * Will be used the prefix the fields names and ids to avoid conflicts with naive properties
         */
        "inputPrefix"?: string;
        /**
          * The label text
         */
        "label": string;
        /**
          * defines the maximum accepted value (inclusive)
         */
        "max"?: number | string;
        /**
          * defines the maximum accepted length
         */
        "maxlength"?: number | string;
        /**
          * defines the minimum accepted value (inclusive)
         */
        "min"?: number | string;
        /**
          * defines the minimum accepted length
         */
        "minlength"?: number | string;
        /**
          * defines the accepted REGEXP pattern
         */
        "pattern"?: string;
        /**
          * Placeholder attribute
         */
        "placeholder"?: string;
        /**
          * HTML5 validation methods. Will be bound via {@link bindNativeInput} during the 'componentWillLoad' lifecyle
          * @see UIInputElement #reportValidity
          * @see HTMLInputElement #reportValidity
         */
        "reportValidity": () => Promise<any>;
        /**
          * Sets the field as required when set to true
         */
        "required": boolean | "true" | "false";
        /**
          * Resets the field value
         */
        "reset": () => Promise<void>;
        /**
          * HTML5 validation methods. Will be bound via {@link bindNativeInput} during the 'componentWillLoad' lifecyle
          * @see UIInputElement #setCustomValidity
          * @see HTMLInputElement #setCustomValidity
         */
        "setCustomValidity": (errors: string) => Promise<any>;
        /**
          * defined the accepted value step
         */
        "step"?: number | string;
        /**
          * Subtype attribute. used for custom validation
         */
        "subtype"?: string;
        /**
          * The field type
         */
        "type": "text" | "number" | "date" | "email" | "url";
        /**
          * value holding attribute
         */
        "value": string;
    }
    interface FormValidateSubmit {
        /**
          * Standard HTML Form action 'url to call'. When defined the form will perform the request with the normal form data. Otherwise will raise a {@link submitEvent}
         */
        "action"?: string;
        /**
          * Enables/disables custom validators and custom error messages
         */
        "customValidation": boolean;
        /**
          * The form definition according to {@link FormDefinition} in string or object format. If none is provided, the HTML content will be displayed
         */
        "formDefinition"?: string | FormDefinition;
        /**
          * Translates to the inner form's id attribute
         */
        "formId": string;
        /**
          * To avoid conflicts it's better to prefix id and names
         */
        "inputPrefix"?: string;
        /**
          * HTML VERB. defaults to POST
         */
        "method"?: "GET" | "POST" | "PUT";
        /**
          * Triggers field validation whenever it's value changes
         */
        "validateOnChange": boolean;
    }
    interface IonicUiInputElement {
        /**
          * @param form
          * @see UIInputElement #bindNativeEvents
         */
        "bindNativeEvents": (form: FormDefinition) => Promise<void>;
        /**
          * HTML5 validation methods. Will be bound via {@link bindNativeInput} during the 'componentWillLoad' lifecyle
          * @see UIInputElement #checkValidity
          * @see HTMLInputElement #checkValidity
         */
        "checkValidity": () => Promise<any>;
        /**
          * defines if the clear button shows
         */
        "clearInput": boolean;
        /**
          * sets the field as disabled
         */
        "disabled"?: boolean;
        /**
          * Retrieves the native {@link HTMLInputElement}
         */
        "getNativeElement": () => Promise<HTMLInputElement>;
        /**
          * Returns the field value
         */
        "getValue": () => Promise<any>;
        /**
          * will translate to the form id attribute
         */
        "inputId": string;
        /**
          * will translate to the form name attribute
         */
        "inputName": string;
        /**
          * Will be used the prefix the fields names and ids to avoid conflicts with naive properties
         */
        "inputPrefix"?: string;
        /**
          * The label text
         */
        "label"?: string;
        /**
          * Defines the Ionic label position
         */
        "labelPosition": "fixed" | "floating" | "stacked";
        /**
          * defines the Ion-item lines
         */
        "lines": "inset" | "full" | "none";
        /**
          * defines the maximum accepted value (inclusive)
         */
        "max"?: string;
        /**
          * defines the maximum accepted length
         */
        "maxlength"?: number;
        /**
          * defines the minimum accepted value (inclusive)
         */
        "min"?: string;
        /**
          * defines the minimum accepted length
         */
        "minlength"?: number;
        /**
          * defines the accepted REGEXP pattern
         */
        "pattern"?: string;
        /**
          * Placeholder attribute
         */
        "placeholder"?: string;
        /**
          * HTML5 validation methods. Will be bound via {@link bindNativeInput} during the 'componentWillLoad' lifecyle
          * @see UIInputElement #reportValidity
          * @see HTMLInputElement #reportValidity
         */
        "reportValidity": () => Promise<any>;
        /**
          * Sets the field as required when set to true
         */
        "required": boolean;
        /**
          * Resets the field value
         */
        "reset": () => Promise<void>;
        /**
          * HTML5 validation methods. Will be bound via {@link bindNativeInput} during the 'componentWillLoad' lifecyle
          * @see UIInputElement #setCustomValidity
          * @see HTMLInputElement #setCustomValidity
         */
        "setCustomValidity": (errors: string) => Promise<any>;
        /**
          * defined the accepted value step
         */
        "step"?: string;
        /**
          * Subtype attribute. used for custom validation
         */
        "subtype"?: string;
        /**
          * The field type
         */
        "type": TextFieldTypes;
        /**
          * value holding attribute
         */
        "value": string;
    }
}
declare global {
    interface HTMLBasicUiInputElementElement extends Components.BasicUiInputElement, HTMLStencilElement {
    }
    var HTMLBasicUiInputElementElement: {
        prototype: HTMLBasicUiInputElementElement;
        new (): HTMLBasicUiInputElementElement;
    };
    interface HTMLFormValidateSubmitElement extends Components.FormValidateSubmit, HTMLStencilElement {
    }
    var HTMLFormValidateSubmitElement: {
        prototype: HTMLFormValidateSubmitElement;
        new (): HTMLFormValidateSubmitElement;
    };
    interface HTMLIonicUiInputElementElement extends Components.IonicUiInputElement, HTMLStencilElement {
    }
    var HTMLIonicUiInputElementElement: {
        prototype: HTMLIonicUiInputElementElement;
        new (): HTMLIonicUiInputElementElement;
    };
    interface HTMLElementTagNameMap {
        "basic-ui-input-element": HTMLBasicUiInputElementElement;
        "form-validate-submit": HTMLFormValidateSubmitElement;
        "ionic-ui-input-element": HTMLIonicUiInputElementElement;
    }
}
declare namespace LocalJSX {
    interface BasicUiInputElement {
        /**
          * sets the field as disabled
         */
        "disabled"?: boolean;
        /**
          * will translate to the form id attribute
         */
        "inputId"?: string;
        /**
          * will translate to the form name attribute
         */
        "inputName"?: string;
        /**
          * Will be used the prefix the fields names and ids to avoid conflicts with naive properties
         */
        "inputPrefix"?: string;
        /**
          * The label text
         */
        "label"?: string;
        /**
          * defines the maximum accepted value (inclusive)
         */
        "max"?: number | string;
        /**
          * defines the maximum accepted length
         */
        "maxlength"?: number | string;
        /**
          * defines the minimum accepted value (inclusive)
         */
        "min"?: number | string;
        /**
          * defines the minimum accepted length
         */
        "minlength"?: number | string;
        /**
          * defines the accepted REGEXP pattern
         */
        "pattern"?: string;
        /**
          * Placeholder attribute
         */
        "placeholder"?: string;
        /**
          * Sets the field as required when set to true
         */
        "required"?: boolean | "true" | "false";
        /**
          * defined the accepted value step
         */
        "step"?: number | string;
        /**
          * Subtype attribute. used for custom validation
         */
        "subtype"?: string;
        /**
          * The field type
         */
        "type"?: "text" | "number" | "date" | "email" | "url";
        /**
          * value holding attribute
         */
        "value"?: string;
    }
    interface FormValidateSubmit {
        /**
          * Standard HTML Form action 'url to call'. When defined the form will perform the request with the normal form data. Otherwise will raise a {@link submitEvent}
         */
        "action"?: string;
        /**
          * Enables/disables custom validators and custom error messages
         */
        "customValidation"?: boolean;
        /**
          * The form definition according to {@link FormDefinition} in string or object format. If none is provided, the HTML content will be displayed
         */
        "formDefinition"?: string | FormDefinition;
        /**
          * Translates to the inner form's id attribute
         */
        "formId"?: string;
        /**
          * To avoid conflicts it's better to prefix id and names
         */
        "inputPrefix"?: string;
        /**
          * HTML VERB. defaults to POST
         */
        "method"?: "GET" | "POST" | "PUT";
        /**
          * Event is raised when the form is reset
          * @event resetEvent
         */
        "onResetEvent"?: (event: CustomEvent<any>) => void;
        /**
          * Event with the form data is raised if no form {@link action} is defined
          * @event submitEvent
         */
        "onSubmitEvent"?: (event: CustomEvent<FormResult>) => void;
        /**
          * Triggers field validation whenever it's value changes
         */
        "validateOnChange"?: boolean;
    }
    interface IonicUiInputElement {
        /**
          * defines if the clear button shows
         */
        "clearInput"?: boolean;
        /**
          * sets the field as disabled
         */
        "disabled"?: boolean;
        /**
          * will translate to the form id attribute
         */
        "inputId"?: string;
        /**
          * will translate to the form name attribute
         */
        "inputName"?: string;
        /**
          * Will be used the prefix the fields names and ids to avoid conflicts with naive properties
         */
        "inputPrefix"?: string;
        /**
          * The label text
         */
        "label"?: string;
        /**
          * Defines the Ionic label position
         */
        "labelPosition"?: "fixed" | "floating" | "stacked";
        /**
          * defines the Ion-item lines
         */
        "lines"?: "inset" | "full" | "none";
        /**
          * defines the maximum accepted value (inclusive)
         */
        "max"?: string;
        /**
          * defines the maximum accepted length
         */
        "maxlength"?: number;
        /**
          * defines the minimum accepted value (inclusive)
         */
        "min"?: string;
        /**
          * defines the minimum accepted length
         */
        "minlength"?: number;
        /**
          * defines the accepted REGEXP pattern
         */
        "pattern"?: string;
        /**
          * Placeholder attribute
         */
        "placeholder"?: string;
        /**
          * Sets the field as required when set to true
         */
        "required"?: boolean;
        /**
          * defined the accepted value step
         */
        "step"?: string;
        /**
          * Subtype attribute. used for custom validation
         */
        "subtype"?: string;
        /**
          * The field type
         */
        "type"?: TextFieldTypes;
        /**
          * value holding attribute
         */
        "value"?: string;
    }
    interface IntrinsicElements {
        "basic-ui-input-element": BasicUiInputElement;
        "form-validate-submit": FormValidateSubmit;
        "ionic-ui-input-element": IonicUiInputElement;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "basic-ui-input-element": LocalJSX.BasicUiInputElement & JSXBase.HTMLAttributes<HTMLBasicUiInputElementElement>;
            "form-validate-submit": LocalJSX.FormValidateSubmit & JSXBase.HTMLAttributes<HTMLFormValidateSubmitElement>;
            "ionic-ui-input-element": LocalJSX.IonicUiInputElement & JSXBase.HTMLAttributes<HTMLIonicUiInputElementElement>;
        }
    }
}
